// src/apps/copybook/components/ControlPanel.tsx
import type { GridType } from '@copybook/interfaces'
import { DEFAULT_CONFIG, FONT_WEIGHTS, GRID_TYPES } from '@copybook/config'
import { A4_WIDTH_MM } from '@copybook/constants'
import { FONTS } from '@copybook/config'
import {
  copybookFontFamily,
  copybookFontOffsetY,
  copybookFontSize,
  copybookFontWeight,
  copybookGridSize,
  copybookGridType,
  copybookHighlightFirst,
  copybookInsertEmptyCol,
  copybookInsertEmptyRow,
  copybookLineColor,
  copybookMargin,
  copybookRowGap,
  copybookText,
  copybookTraceColor,
  copybookTraceCount,
} from '@copybook/store'
import { useStore } from '@nanostores/react'
import { useState } from 'react'
import { Button } from '@/components/ui/button'
import { Field, FieldContent, FieldGroup, FieldLabel, FieldSeparator, FieldSet } from '@/components/ui/field'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Slider } from '@/components/ui/slider'
import { Switch } from '@/components/ui/switch'
import ColorPickerDialog from './ColorPickerDialog'
import ExportButton from './ExportButton'
import FontPickerDialog from './FontPickerDialog'
import MarginDialog from './MarginDialog'
import TextInputDialog from './TextInputDialog'

const groupCls = 'bg-background rounded-md border px-3 py-[2px] shadow-xs'
const sepCls = 'h-px my-0'

export default function ControlPanel() {
  const text = useStore(copybookText)
  const gridType = useStore(copybookGridType)
  const gridSize = useStore(copybookGridSize)
  const rowGap = useStore(copybookRowGap)
  const fontWeight = useStore(copybookFontWeight)
  const fontSize = useStore(copybookFontSize)
  const fontOffsetY = useStore(copybookFontOffsetY)
  const traceCount = useStore(copybookTraceCount)
  const traceColor = useStore(copybookTraceColor)
  const lineColor = useStore(copybookLineColor)
  const highlightFirst = useStore(copybookHighlightFirst)
  const insertEmptyRow = useStore(copybookInsertEmptyRow)
  const insertEmptyCol = useStore(copybookInsertEmptyCol)
  const margin = useStore(copybookMargin)
  const fontFamily = useStore(copybookFontFamily)

  const colsPerRow = Math.floor((A4_WIDTH_MM - margin.left - margin.right) / gridSize) || 1
  const contentCols = insertEmptyCol ? Math.ceil(colsPerRow / 2) : colsPerRow
  const maxTraceCount = Math.max(contentCols, 1)

  const [showTextDialog, setShowTextDialog] = useState(false)
  const [showMarginDialog, setShowMarginDialog] = useState(false)
  const [showFontDialog, setShowFontDialog] = useState(false)
  const [showTraceColorPicker, setShowTraceColorPicker] = useState(false)
  const [showLineColorPicker, setShowLineColorPicker] = useState(false)

  function resetAll() {
    copybookText.set(DEFAULT_CONFIG.text)
    copybookGridType.set(DEFAULT_CONFIG.gridType)
    copybookGridSize.set(DEFAULT_CONFIG.gridSize)
    copybookRowGap.set(DEFAULT_CONFIG.rowGap)
    copybookMargin.set({ ...DEFAULT_CONFIG.margin })
    copybookFontFamily.set(DEFAULT_CONFIG.fontFamily)
    copybookFontWeight.set(DEFAULT_CONFIG.fontWeight)
    copybookFontSize.set(DEFAULT_CONFIG.fontSize)
    copybookFontOffsetY.set(DEFAULT_CONFIG.fontOffsetY)
    copybookTraceCount.set(DEFAULT_CONFIG.traceCount)
    copybookTraceColor.set(DEFAULT_CONFIG.traceColor)
    copybookLineColor.set(DEFAULT_CONFIG.lineColor)
    copybookHighlightFirst.set(DEFAULT_CONFIG.highlightFirst)
    copybookInsertEmptyRow.set(DEFAULT_CONFIG.insertEmptyRow)
    copybookInsertEmptyCol.set(DEFAULT_CONFIG.insertEmptyCol)
  }

  return (
    <div className="flex flex-col gap-3 text-sm">
      <div className="grid grid-cols-2 gap-2">
        <Button variant="outline" onClick={resetAll}>
          重置
        </Button>
        <ExportButton />
      </div>

      <button
        className="flex h-9 items-center rounded-md border px-3 shadow-xs hover:bg-accent"
        onClick={() => setShowTextDialog(true)}
      >
        <span className="truncate">{text || '点击输入汉字'}</span>
      </button>

      <FieldSet className={groupCls}>
        <FieldGroup className="gap-0">
          <Field orientation="horizontal" className="h-9 items-center justify-between gap-6">
            <FieldLabel className="text-slate-700 dark:text-slate-200">首字高亮</FieldLabel>
            <Switch checked={highlightFirst} onCheckedChange={v => copybookHighlightFirst.set(v)} />
          </Field>
          <FieldSeparator className={sepCls} />
          <Field orientation="horizontal" className="h-9 items-center justify-between gap-6">
            <FieldLabel className="text-slate-700 dark:text-slate-200">插入空行</FieldLabel>
            <Switch checked={insertEmptyRow} onCheckedChange={v => copybookInsertEmptyRow.set(v)} />
          </Field>
          <FieldSeparator className={sepCls} />
          <Field orientation="horizontal" className="h-9 items-center justify-between gap-6">
            <FieldLabel className="text-slate-700 dark:text-slate-200">插入空列</FieldLabel>
            <Switch checked={insertEmptyCol} onCheckedChange={v => copybookInsertEmptyCol.set(v)} />
          </Field>
        </FieldGroup>
      </FieldSet>

      <FieldSet className={groupCls}>
        <FieldGroup className="gap-0">
          <Field orientation="horizontal" className="h-9 !items-center gap-6">
            <FieldLabel className="!flex-none w-14 shrink-0 text-slate-700 dark:text-slate-200">方格类型</FieldLabel>
            <FieldContent className="flex-1">
              <Select value={gridType} onValueChange={v => copybookGridType.set(v as GridType)}>
                <SelectTrigger className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {GRID_TYPES.map(gt => (
                    <SelectItem key={gt.value} value={gt.value}>{gt.label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </FieldContent>
          </Field>
          <FieldSeparator className={sepCls} />
          <Field orientation="horizontal" className="h-9 !items-center gap-6">
            <FieldLabel className="!flex-none w-14 shrink-0 text-slate-700 dark:text-slate-200">方格大小</FieldLabel>
            <FieldContent className="!flex-row items-center gap-2">
              <Slider className="flex-1" value={[gridSize]} min={6} max={60} step={1} onValueChange={([v]) => copybookGridSize.set(v)} />
              <span className="w-10 shrink-0 text-right text-xs text-muted-foreground">
                {gridSize}
                mm
              </span>
            </FieldContent>
          </Field>
          <FieldSeparator className={sepCls} />
          <Field orientation="horizontal" className="h-9 !items-center gap-6">
            <FieldLabel className="!flex-none w-14 shrink-0 text-slate-700 dark:text-slate-200">行间距</FieldLabel>
            <FieldContent className="!flex-row items-center gap-2">
              <Slider className="flex-1" value={[rowGap]} min={0} max={10} step={1} onValueChange={([v]) => copybookRowGap.set(v)} />
              <span className="w-10 shrink-0 text-right text-xs text-muted-foreground">
                {rowGap}
                mm
              </span>
            </FieldContent>
          </Field>
          <FieldSeparator className={sepCls} />
          <button className="flex h-9 w-full items-center justify-between hover:bg-accent" onClick={() => setShowMarginDialog(true)}>
            <FieldLabel className="text-slate-700 dark:text-slate-200">页边距</FieldLabel>
            <span className="text-muted-foreground">
              {margin.top}
              ,
              {margin.right}
              ,
              {margin.bottom}
              ,
              {margin.left}
            </span>
          </button>
        </FieldGroup>
      </FieldSet>

      <FieldSet className={groupCls}>
        <FieldGroup className="gap-0">
          <button className="flex h-9 w-full items-center justify-between hover:bg-accent" onClick={() => setShowFontDialog(true)}>
            <FieldLabel className="text-slate-700 dark:text-slate-200">字体</FieldLabel>
            <span className="text-muted-foreground">{FONTS.find(f => f.id === fontFamily)?.label ?? '选择...'}</span>
          </button>
          <FieldSeparator className={sepCls} />
          <Field orientation="horizontal" className="h-9 !items-center gap-6">
            <FieldLabel className="!flex-none w-14 shrink-0 text-slate-700 dark:text-slate-200">字体粗细</FieldLabel>
            <FieldContent className="flex-1">
              <Select value={fontWeight} onValueChange={v => copybookFontWeight.set(v)}>
                <SelectTrigger className="w-full">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {FONT_WEIGHTS.map(fw => (
                    <SelectItem key={fw.value} value={fw.value}>{fw.label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </FieldContent>
          </Field>
          <FieldSeparator className={sepCls} />
          <Field orientation="horizontal" className="h-9 !items-center gap-6">
            <FieldLabel className="!flex-none w-14 shrink-0 text-slate-700 dark:text-slate-200">字体大小</FieldLabel>
            <FieldContent className="!flex-row items-center gap-2">
              <Slider className="flex-1" value={[fontSize]} min={48} max={128} step={1} onValueChange={([v]) => copybookFontSize.set(v)} />
              <span className="w-10 shrink-0 text-right text-xs text-muted-foreground">
                {fontSize}
                %
              </span>
            </FieldContent>
          </Field>
          <FieldSeparator className={sepCls} />
          <Field orientation="horizontal" className="h-9 !items-center gap-6">
            <FieldLabel className="!flex-none w-14 shrink-0 text-slate-700 dark:text-slate-200">上下偏移</FieldLabel>
            <FieldContent className="!flex-row items-center gap-2">
              <Slider className="flex-1" value={[fontOffsetY]} min={-50} max={50} step={1} onValueChange={([v]) => copybookFontOffsetY.set(v)} />
              <span className="w-10 shrink-0 text-right text-xs text-muted-foreground">
                {fontOffsetY}
                %
              </span>
            </FieldContent>
          </Field>
        </FieldGroup>
      </FieldSet>

      <FieldSet className={groupCls}>
        <FieldGroup className="gap-0">
          <Field orientation="horizontal" className="h-9 !items-center gap-6">
            <FieldLabel className="!flex-none w-14 shrink-0 text-slate-700 dark:text-slate-200">描红数量</FieldLabel>
            <FieldContent className="!flex-row items-center gap-2">
              <Slider className="flex-1" value={[traceCount]} min={0} max={maxTraceCount} step={1} onValueChange={([v]) => copybookTraceCount.set(v)} />
              <span className="w-10 shrink-0 text-right text-xs text-muted-foreground">{traceCount}</span>
            </FieldContent>
          </Field>
          <FieldSeparator className={sepCls} />
          <Field orientation="horizontal" className="h-9 items-center justify-between gap-6">
            <FieldLabel className="text-slate-700 dark:text-slate-200">描红颜色</FieldLabel>
            <button
              className="h-7 w-7 rounded-md border"
              style={{ backgroundColor: traceColor === 'black' ? '#000' : traceColor }}
              onClick={() => setShowTraceColorPicker(true)}
            />
          </Field>
          <FieldSeparator className={sepCls} />
          <Field orientation="horizontal" className="h-9 items-center justify-between gap-6">
            <FieldLabel className="text-slate-700 dark:text-slate-200">线条颜色</FieldLabel>
            <button
              className="h-7 w-7 rounded-md border"
              style={{ backgroundColor: lineColor === 'black' ? '#000' : lineColor }}
              onClick={() => setShowLineColorPicker(true)}
            />
          </Field>
        </FieldGroup>
      </FieldSet>

      <TextInputDialog open={showTextDialog} onOpenChange={setShowTextDialog} />
      <MarginDialog open={showMarginDialog} onOpenChange={setShowMarginDialog} />
      <FontPickerDialog open={showFontDialog} onOpenChange={setShowFontDialog} />
      <ColorPickerDialog
        open={showTraceColorPicker}
        onOpenChange={setShowTraceColorPicker}
        color={traceColor}
        onSelect={v => copybookTraceColor.set(v)}
      />
      <ColorPickerDialog
        open={showLineColorPicker}
        onOpenChange={setShowLineColorPicker}
        color={lineColor}
        onSelect={v => copybookLineColor.set(v)}
      />
    </div>
  )
}

// src/components/copybook/ControlPanel.vue
<script setup lang="ts">
import type { GridType } from '@/interfaces/copybook'
import { useStore } from '@nanostores/vue'
import { ref } from 'vue'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Slider } from '@/components/ui/slider'
import { Switch } from '@/components/ui/switch'
import { FONT_WEIGHTS, GRID_TYPES } from '@/config/copybook.config'
import {
  copybookFontOffsetY,
  copybookFontSize,
  copybookFontWeight,
  copybookGridSize,
  copybookGridType,
  copybookHighlightFirst,
  copybookInsertEmptyCol,
  copybookInsertEmptyRow,
  copybookLineColor,
  copybookRowGap,
  copybookText,
  copybookTraceColor,
  copybookTraceCount,
} from '@/stores/copybook.store'
import ColorPickerDialog from './ColorPickerDialog.vue'
import ExportButton from './ExportButton.vue'
import FontPickerDialog from './FontPickerDialog.vue'
import MarginDialog from './MarginDialog.vue'
import TextInputDialog from './TextInputDialog.vue'

const text = useStore(copybookText)
const gridType = useStore(copybookGridType)
const gridSize = useStore(copybookGridSize)
const rowGap = useStore(copybookRowGap)
const fontWeight = useStore(copybookFontWeight)
const fontSize = useStore(copybookFontSize)
const fontOffsetY = useStore(copybookFontOffsetY)
const traceCount = useStore(copybookTraceCount)
const traceColor = useStore(copybookTraceColor)
const lineColor = useStore(copybookLineColor)
const highlightFirst = useStore(copybookHighlightFirst)
const insertEmptyRow = useStore(copybookInsertEmptyRow)
const insertEmptyCol = useStore(copybookInsertEmptyCol)

const showTextDialog = ref(false)
const showMarginDialog = ref(false)
const showFontDialog = ref(false)
const showTraceColorPicker = ref(false)
const showLineColorPicker = ref(false)
</script>

<template>
  <div class="text-sm flex flex-col gap-5">
    <section>
      <h4 class="text-xs text-gray-400 tracking-wider font-medium mb-2 uppercase">
        文本
      </h4>
      <button
        class="px-3 py-2 text-left border border-gray-200 rounded-md w-full truncate hover:border-gray-300"
        @click="showTextDialog = true"
      >
        {{ text || '点击输入汉字' }}
      </button>
    </section>

    <section>
      <h4 class="text-xs text-gray-400 tracking-wider font-medium mb-2 uppercase">
        显示
      </h4>
      <div class="space-y-2">
        <div class="flex gap-2 items-center">
          <Switch :model-value="highlightFirst" @update:model-value="copybookHighlightFirst.set($event)" />
          <Label>首字高亮</Label>
        </div>
        <div class="flex gap-2 items-center">
          <Switch :model-value="insertEmptyRow" @update:model-value="copybookInsertEmptyRow.set($event)" />
          <Label>插入空行</Label>
        </div>
        <div class="flex gap-2 items-center">
          <Switch :model-value="insertEmptyCol" @update:model-value="copybookInsertEmptyCol.set($event)" />
          <Label>插入空列</Label>
        </div>
      </div>
    </section>

    <section>
      <h4 class="text-xs text-gray-400 tracking-wider font-medium mb-2 uppercase">
        方格
      </h4>
      <div class="space-y-3">
        <div>
          <Label class="text-muted-foreground mb-1 block">方格类型</Label>
          <Select :model-value="gridType" @update:model-value="copybookGridType.set($event as GridType)">
            <SelectTrigger class="w-full">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="gt in GRID_TYPES" :key="gt.value" :value="gt.value">
                {{ gt.label }}
              </SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <div class="text-muted-foreground mb-1 flex justify-between">
            <Label>方格大小</Label>
            <Label>{{ gridSize }}mm</Label>
          </div>
          <Slider :model-value="[gridSize]" :min="6" :max="60" :step="1" @update:model-value="copybookGridSize.set($event![0])" />
        </div>
        <div>
          <div class="text-muted-foreground mb-1 flex justify-between">
            <Label>行间距</Label>
            <Label>{{ rowGap }}mm</Label>
          </div>
          <Slider :model-value="[rowGap]" :min="0" :max="10" :step="1" @update:model-value="copybookRowGap.set($event![0])" />
        </div>
        <button
          class="px-3 py-1.5 text-left border border-gray-200 rounded-md w-full hover:bg-gray-50"
          @click="showMarginDialog = true"
        >
          页边距设置...
        </button>
      </div>
    </section>

    <section>
      <h4 class="text-xs text-gray-400 tracking-wider font-medium mb-2 uppercase">
        字体
      </h4>
      <div class="space-y-3">
        <button
          class="px-3 py-1.5 text-left border border-gray-200 rounded-md w-full hover:bg-gray-50"
          @click="showFontDialog = true"
        >
          字体选择...
        </button>
        <div>
          <Label class="text-muted-foreground mb-1 block">字体粗细</Label>
          <Select :model-value="fontWeight" @update:model-value="copybookFontWeight.set($event)">
            <SelectTrigger class="w-full">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem v-for="fw in FONT_WEIGHTS" :key="fw.value" :value="fw.value">
                {{ fw.label }}
              </SelectItem>
            </SelectContent>
          </Select>
        </div>
        <div>
          <div class="text-muted-foreground mb-1 flex justify-between">
            <Label>字体大小</Label>
            <Label>{{ fontSize }}%</Label>
          </div>
          <Slider :model-value="[fontSize]" :min="48" :max="128" :step="1" @update:model-value="copybookFontSize.set($event![0])" />
        </div>
        <div>
          <div class="text-muted-foreground mb-1 flex justify-between">
            <Label>上下偏移</Label>
            <Label>{{ fontOffsetY }}%</Label>
          </div>
          <Slider :model-value="[fontOffsetY]" :min="-50" :max="50" :step="1" @update:model-value="copybookFontOffsetY.set($event![0])" />
        </div>
      </div>
    </section>

    <section>
      <h4 class="text-xs text-gray-400 tracking-wider font-medium mb-2 uppercase">
        描红
      </h4>
      <div class="space-y-3">
        <div>
          <div class="text-muted-foreground mb-1 flex justify-between">
            <Label>描红数量</Label>
            <Label>{{ traceCount }}</Label>
          </div>
          <Slider :model-value="[traceCount]" :min="1" :max="20" :step="1" @update:model-value="copybookTraceCount.set($event![0])" />
        </div>
        <div class="flex gap-2 items-center">
          <Label class="text-muted-foreground">描红颜色</Label>
          <button
            class="border border-gray-200 rounded-md h-7 w-7"
            :style="{ backgroundColor: traceColor === 'black' ? '#000' : traceColor }"
            @click="showTraceColorPicker = true"
          />
        </div>
        <div class="flex gap-2 items-center">
          <Label class="text-muted-foreground">线条颜色</Label>
          <button
            class="border border-gray-200 rounded-md h-7 w-7"
            :style="{ backgroundColor: lineColor === 'black' ? '#000' : lineColor }"
            @click="showLineColorPicker = true"
          />
        </div>
      </div>
    </section>

    <section class="pt-2">
      <ExportButton />
    </section>

    <TextInputDialog v-model:visible="showTextDialog" />
    <MarginDialog v-model:visible="showMarginDialog" />
    <FontPickerDialog v-model:visible="showFontDialog" />
    <ColorPickerDialog
      :visible="showTraceColorPicker"
      :color="traceColor"
      @select="copybookTraceColor.set($event)"
      @close="showTraceColorPicker = false"
    />
    <ColorPickerDialog
      :visible="showLineColorPicker"
      :color="lineColor"
      @select="copybookLineColor.set($event)"
      @close="showLineColorPicker = false"
    />
  </div>
</template>
