// src/components/widgets/NavMenu.vue
<script setup lang="ts">
import type { NavBarItem } from '@/config/header.config'
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from '@/components/ui/navigation-menu'

interface Props {
  items: NavBarItem[]
}

defineProps<Props>()
</script>

<template>
  <NavigationMenu class="flex-auto">
    <NavigationMenuList>
      <NavigationMenuItem v-for="item in items" :key="item.text">
        <template v-if="item.children?.length">
          <NavigationMenuTrigger>{{ item.text }}</NavigationMenuTrigger>
          <NavigationMenuContent>
            <NavigationMenuLink
              v-for="child in item.children"
              :key="child.text"
              :href="child.link"
              :class="navigationMenuTriggerStyle()"
            >
              {{ child.text }}
            </NavigationMenuLink>
          </NavigationMenuContent>
        </template>
        <template v-else>
          <NavigationMenuLink :href="item.link" :class="navigationMenuTriggerStyle()">
            {{ item.text }}
          </NavigationMenuLink>
        </template>
      </NavigationMenuItem>
    </NavigationMenuList>
  </NavigationMenu>
</template>

// src/components/widgets/NavMenu.tsx
import {
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuLink,
  NavigationMenuList,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
} from '@/components/ui/navigation-menu'

interface NavBarItem {
  text: string
  link?: string
  children?: NavBarItem[]
}

interface Props {
  items: NavBarItem[]
}

export default function NavMenu({ items }: Props) {
  return (
    <NavigationMenu className="flex-auto">
      <NavigationMenuList>
        {items.map(item => (
          <NavigationMenuItem key={item.text}>
            {item.children?.length
              ? (
                  <>
                    <NavigationMenuTrigger>{item.text}</NavigationMenuTrigger>
                    <NavigationMenuContent>
                      {item.children.map(child => (
                        <NavigationMenuLink
                          key={child.text}
                          href={child.link}
                          className={navigationMenuTriggerStyle()}
                        >
                          {child.text}
                        </NavigationMenuLink>
                      ))}
                    </NavigationMenuContent>
                  </>
                )
              : (
                  <NavigationMenuLink href={item.link} className={navigationMenuTriggerStyle()}>
                    {item.text}
                  </NavigationMenuLink>
                )}
          </NavigationMenuItem>
        ))}
      </NavigationMenuList>
    </NavigationMenu>
  )
}
