// src/components/widgets/ThemeToggle.tsx
import { Icon } from '@iconify/react'
import { useStore } from '@nanostores/react'
import * as AppStore from '@/stores/app.store'

export default function ThemeToggle() {
  const theme = useStore(AppStore.theme)

  function onToggleTheme() {
    const value = theme === 'dark' ? 'light' : 'dark'
    AppStore.updateTheme(value)
  }

  return (
    <div className="cursor-pointer" onClick={onToggleTheme}>
      {theme === 'dark'
        ? <Icon icon="icon-park-outline:moon" className="text-[16px]" />
        : <Icon icon="icon-park-outline:sun-one" className="text-[16px]" />}
    </div>
  )
}

// src/components/widgets/ThemeToggle.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue'
import { useStore } from '@nanostores/vue'
import * as AppStore from '../../stores/app.store'

const theme = useStore(AppStore.theme)

/**
 * 切换主题
 */
function onToggleTheme() {
  const value = theme.value === 'dark' ? 'light' : 'dark'
  AppStore.updateTheme(value)
}
</script>

<template>
  <div class="cursor-pointer" @click="onToggleTheme">
    <Icon v-if="theme === 'dark'" icon="icon-park-outline:moon" class="text-[16px]" />
    <Icon v-else icon="icon-park-outline:sun-one" class="text-[16px]" />
  </div>
</template>
